"""fix: remove name

Revision ID: a8246b064c6b
Revises: de5696fdc245
Create Date: 2026-05-30 11:25:09.693825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8246b064c6b'
down_revision: Union[str, None] = 'de5696fdc245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_name', table_name='users')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index('ix_users_name', 'users', ['name'], unique=True)
    # ### end Alembic commands ###
