"""feat: update tables

Revision ID: cc41f0133f68
Revises: 33b5671f398f
Create Date: 2026-05-29 23:50:08.020939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc41f0133f68'
down_revision: Union[str, None] = '33b5671f398f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chatbots_id', table_name='chatbots')
    op.drop_index('ix_chatbots_static_token', table_name='chatbots')
    op.drop_index('ix_chatbots_user_id', table_name='chatbots')
    op.drop_table('chatbots')
    op.drop_index('ix_chatbot_states_conversation_id', table_name='chatbot_states')
    op.drop_index('ix_chatbot_states_created_at', table_name='chatbot_states')
    op.drop_index('ix_chatbot_states_id', table_name='chatbot_states')
    op.drop_table('chatbot_states')
    op.drop_index('ix_conversations_chatbot_id', table_name='conversations')
    op.drop_index('ix_conversations_created_at', table_name='conversations')
    op.drop_index('ix_conversations_id', table_name='conversations')
    op.drop_index('ix_conversations_user_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_chatbot_nodes_id', table_name='chatbot_nodes')
    op.drop_table('chatbot_nodes')
    op.drop_index('ix_chatbot_agents_id', table_name='chatbot_agents')
    op.drop_table('chatbot_agents')
    op.drop_index('ix_chat_messages_conversation_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_created_at', table_name='chat_messages')
    op.drop_index('ix_chat_messages_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_chatbot_tools_id', table_name='chatbot_tools')
    op.drop_table('chatbot_tools')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_tools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chatbot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tool_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tool_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tool_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('timeout_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requires_auth', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name='chatbot_tools_chatbot_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chatbot_tools_pkey')
    )
    op.create_index('ix_chatbot_tools_id', 'chatbot_tools', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tool_calls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tool_call_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('agent_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('node_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='chat_messages_conversation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_messages_pkey')
    )
    op.create_index('ix_chat_messages_id', 'chat_messages', ['id'], unique=False)
    op.create_index('ix_chat_messages_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_index('ix_chat_messages_conversation_id', 'chat_messages', ['conversation_id'], unique=False)
    op.create_table('chatbot_agents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chatbot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agent_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name='chatbot_agents_chatbot_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chatbot_agents_pkey')
    )
    op.create_index('ix_chatbot_agents_id', 'chatbot_agents', ['id'], unique=False)
    op.create_table('chatbot_nodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chatbot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('node_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('node_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('node_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('edges', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_entry_point', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_exit_point', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('timeout_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name='chatbot_nodes_chatbot_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chatbot_nodes_pkey')
    )
    op.create_index('ix_chatbot_nodes_id', 'chatbot_nodes', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('conversations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('chatbot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('custom_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('context_window', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name='conversations_chatbot_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey'),
    sa.UniqueConstraint('session_id', name='conversations_session_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_id', 'conversations', ['id'], unique=False)
    op.create_index('ix_conversations_created_at', 'conversations', ['created_at'], unique=False)
    op.create_index('ix_conversations_chatbot_id', 'conversations', ['chatbot_id'], unique=False)
    op.create_table('chatbot_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chatbot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('locked_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('locked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lock_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_node', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('message_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name='chatbot_states_chatbot_id_fkey'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='chatbot_states_conversation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chatbot_states_pkey')
    )
    op.create_index('ix_chatbot_states_id', 'chatbot_states', ['id'], unique=False)
    op.create_index('ix_chatbot_states_created_at', 'chatbot_states', ['created_at'], unique=False)
    op.create_index('ix_chatbot_states_conversation_id', 'chatbot_states', ['conversation_id'], unique=False)
    op.create_table('chatbots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('graph_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('max_context_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('static_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='chatbots_pkey')
    )
    op.create_index('ix_chatbots_user_id', 'chatbots', ['user_id'], unique=False)
    op.create_index('ix_chatbots_static_token', 'chatbots', ['static_token'], unique=True)
    op.create_index('ix_chatbots_id', 'chatbots', ['id'], unique=False)
    # ### end Alembic commands ###
