"""feat: init database creation

Revision ID: db3427852ef1
Revises: 
Create Date: 2026-05-30 08:22:16.212773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3427852ef1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('variable_pattern', sa.String(length=500), nullable=True),
    sa.Column('dynamic_script', sa.Text(), nullable=True),
    sa.Column('input_variables', sa.JSON(), nullable=True),
    sa.Column('output_variables', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('agent_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_agents_id'), 'chatbot_agents', ['id'], unique=False)
    op.create_table('chatbots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('graph_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_context_length', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('static_token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbots_id'), 'chatbots', ['id'], unique=False)
    op.create_index(op.f('ix_chatbots_static_token'), 'chatbots', ['static_token'], unique=True)
    op.create_index(op.f('ix_chatbots_user_id'), 'chatbots', ['user_id'], unique=False)
    op.create_table('chatbot_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chatbot_id', sa.UUID(), nullable=False),
    sa.Column('state_data', sa.JSON(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=True),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(), nullable=True),
    sa.Column('current_node', sa.String(length=255), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_states_created_at'), 'chatbot_states', ['created_at'], unique=False)
    op.create_index(op.f('ix_chatbot_states_id'), 'chatbot_states', ['id'], unique=False)
    op.create_table('chatbot_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chatbot_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tool_type', sa.String(length=100), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS', name='httpmethod'), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.Column('is_code', sa.Boolean(), nullable=True),
    sa.Column('code_content', sa.Text(), nullable=True),
    sa.Column('variable_pattern', sa.String(length=500), nullable=True),
    sa.Column('dynamic_script', sa.Text(), nullable=True),
    sa.Column('input_variables', sa.JSON(), nullable=True),
    sa.Column('output_variables', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tool_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('tool_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_tools_id'), 'chatbot_tools', ['id'], unique=False)
    op.create_table('chatbot_agent_tools',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['chatbot_agents.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['chatbot_tools.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    op.create_table('chatbot_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chatbot_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('tool_id', sa.UUID(), nullable=True),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('node_config', sa.JSON(), nullable=True),
    sa.Column('edges', sa.JSON(), nullable=True),
    sa.Column('is_entry_point', sa.Boolean(), nullable=True),
    sa.Column('is_exit_point', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['chatbot_agents.id'], ),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['chatbot_tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_nodes_id'), 'chatbot_nodes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatbot_nodes_id'), table_name='chatbot_nodes')
    op.drop_table('chatbot_nodes')
    op.drop_table('chatbot_agent_tools')
    op.drop_index(op.f('ix_chatbot_tools_id'), table_name='chatbot_tools')
    op.drop_table('chatbot_tools')
    op.drop_index(op.f('ix_chatbot_states_id'), table_name='chatbot_states')
    op.drop_index(op.f('ix_chatbot_states_created_at'), table_name='chatbot_states')
    op.drop_table('chatbot_states')
    op.drop_index(op.f('ix_chatbots_user_id'), table_name='chatbots')
    op.drop_index(op.f('ix_chatbots_static_token'), table_name='chatbots')
    op.drop_index(op.f('ix_chatbots_id'), table_name='chatbots')
    op.drop_table('chatbots')
    op.drop_index(op.f('ix_chatbot_agents_id'), table_name='chatbot_agents')
    op.drop_table('chatbot_agents')
    # ### end Alembic commands ###
